name: Erw&auml;hnenswert
subtitle: ... darum schreibe ich hier

paginate: 5

url: https://blog.lgohlke.de
repository: lkwg82/blog

feed:
  path: rss.xml

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown

sass:
   style: compressed

sitemap: true
theme: jekyll-theme-dinky

host: 0.0.0.0
port: 4000
livereload: true